### ISSUE TITLE
'NoneType' object error

### ISSUE THREAD

**Issue by janosdaru** [fonsecag/FFAST#2]
Hey, 

I get some errors without obviously missing python module. Could you please suggest a fix for this issue?

python main.py 
[ERROR] 'NoneType' object has no attribute 'setStyleSheet'
Traceback (most recent call last):
  File "/home/daru/bin/FFAST/main.py", line 152, in <module>
    qasync.run(main())
  File "/home/daru/anaconda3/lib/python3.9/site-packages/qasync/__init__.py", line 840, in run
    return asyncio.run(*args, **kwargs)
  File "/home/daru/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/daru/anaconda3/lib/python3.9/site-packages/qasync/__init__.py", line 409, in run_until_complete
    return future.result()
  File "/home/daru/bin/FFAST/main.py", line 125, in main
    UI.launch()
  File "/home/daru/bin/FFAST/UI/UIHandler.py", line 88, in launch
    app.setStyleSheet(styleSheet)
AttributeError: 'NoneType' object has no attribute 'setStyleSheet'

**Comment by fonsecag** [comment]
Unfortunately I am unable to reproduce the error myself. Did the installation process as described in the README have an issues? In particular, it is important that the installed PySide6 version is 6.4.2. 

Furthermore, could you please tell me under what OS you are trying to launch FFAST in?

**Comment by janosdaru** [comment]
Sure, I have followed exactly each pip install command. It is a Linux Mint 20.3 Xfce 64-bit.

**Comment by fonsecag** [comment]
I do not have access to a machine with Linux Mint on it at the moment, and unfortunately all the GUI-related issues seem to be tied to the exact os versions people run. My virtual machine did not reproduce the same error but had other library issues.

I have added a new commit that maybe bypasses the issue as a bandaid, though i had no real way to check if it works.

Otherwise, I can always suggest updating all graphic libraries needed for Qt, as shown here https://docs.anaconda.com/free/anaconda/install/linux/ under Prerequisites.

**Comment by janosdaru** [comment]
Many thanks for all your efforts. I have fetched your git changes, and run the 

sudo apt-get install --only-upgrade  libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxcomposite1 is already the newest version (1:0.4.5-1).
libxcursor1 is already the newest version (1:1.2.0-2).
libxi6 is already the newest version (2:1.7.10-0ubuntu1).
libxrandr2 is already the newest version (2:1.5.2-0ubuntu1).
libxss1 is already the newest version (1:1.2.3-1).
libxtst6 is already the newest version (2:1.2.3-1).
libasound2 is already the newest version (1.2.2-2.1ubuntu2.5).
libgl1-mesa-glx is already the newest version (21.2.6-0ubuntu0.1~20.04.2).
libegl1-mesa is already the newest version (21.2.6-0ubuntu0.1~20.04.2).

command.  As shown, all packages are up to date. It still fails the same way. 

Maybe I will check again once I have updated the OS. 

Best
